02/14/2015 09:38:08 AM 
 ping twitter error: 
Traceback (most recent call last):
  File "Social_Media_Pinger.py", line 137, in ping_twitter
    user = api.get_user(auth, screen_name=handle)
  File "/home/maikflow/Documents/python/Freelancer-jobs/social_media_pinger/local/lib/python2.7/site-packages/tweepy/binder.py", line 239, in _call
    return method.execute()
  File "/home/maikflow/Documents/python/Freelancer-jobs/social_media_pinger/local/lib/python2.7/site-packages/tweepy/binder.py", line 223, in execute
    raise TweepError(error_msg, resp)
TweepError: [{u'message': u'Rate limit exceeded', u'code': 88}]
02/14/2015 09:43:35 AM 
 ping twitter error: 
Traceback (most recent call last):
  File "Social_Media_Pinger.py", line 137, in ping_twitter
    user = api.get_user(auth, screen_name=handle)
  File "/home/maikflow/Documents/python/Freelancer-jobs/social_media_pinger/local/lib/python2.7/site-packages/tweepy/binder.py", line 239, in _call
    return method.execute()
  File "/home/maikflow/Documents/python/Freelancer-jobs/social_media_pinger/local/lib/python2.7/site-packages/tweepy/binder.py", line 223, in execute
    raise TweepError(error_msg, resp)
TweepError: [{u'message': u'Rate limit exceeded', u'code': 88}]
